# Generated by Django 5.1.1 on 2024-10-02 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0002_alter_customuser_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
