# Generated by Django 5.0.7 on 2024-08-01 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'Компонент', 'verbose_name_plural': 'Компонент'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Карточка товара', 'verbose_name_plural': 'Карточка товара'},
        ),
    ]
