# Generated by Django 5.0.7 on 2024-07-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии')),
            ],
            options={
                'verbose_name': 'Подарочный набор',
                'verbose_name_plural': 'Подарочные наборы',
            },
        ),
        migrations.AlterModelOptions(
            name='sweetdays',
            options={'verbose_name': 'Сладкие Дни', 'verbose_name_plural': 'Сладкие Дни'},
        ),
    ]
