# Generated by Django 5.0.7 on 2024-08-07 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_product_category_delete_order_delete_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacaronSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название набора')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая цена')),
            ],
            options={
                'verbose_name': 'Набор макарунов',
                'verbose_name_plural': 'Наборы макарунов',
            },
        ),
        migrations.AlterModelOptions(
            name='assemblethesets',
            options={'verbose_name': 'Макарун', 'verbose_name_plural': 'Макаруны'},
        ),
        migrations.RemoveField(
            model_name='assemblethesets',
            name='price',
        ),
        migrations.AddField(
            model_name='assemblethesets',
            name='flavor',
            field=models.CharField(default=1, max_length=100, verbose_name='Вкус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assemblethesets',
            name='image',
            field=models.ImageField(upload_to='macarons/', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='MacaronSetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('macaron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.assemblethesets', verbose_name='Макарун')),
                ('macaron_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.macaronset', verbose_name='Набор макарунов')),
            ],
            options={
                'verbose_name': 'Элемент набора макарунов',
                'verbose_name_plural': 'Элементы наборов макарунов',
            },
        ),
        migrations.AddField(
            model_name='macaronset',
            name='macarons',
            field=models.ManyToManyField(through='polls.MacaronSetItem', to='polls.assemblethesets', verbose_name='Макаруны'),
        ),
    ]
