# Generated by Django 5.0.7 on 2024-08-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_macaronset_alter_assemblethesets_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyKits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('in_cart', models.BooleanField(default=False, verbose_name='В корзине')),
            ],
            options={
                'verbose_name': 'Готовые наборы',
                'verbose_name_plural': 'Готовые наборы',
            },
        ),
        migrations.RemoveField(
            model_name='macaronsetitem',
            name='macaron',
        ),
        migrations.RemoveField(
            model_name='macaronset',
            name='macarons',
        ),
        migrations.RemoveField(
            model_name='macaronsetitem',
            name='macaron_set',
        ),
        migrations.AddField(
            model_name='giftset',
            name='in_cart',
            field=models.BooleanField(default=False, verbose_name='В корзине'),
        ),
        migrations.AddField(
            model_name='sweetdays',
            name='in_cart',
            field=models.BooleanField(default=False, verbose_name='В корзине'),
        ),
        migrations.DeleteModel(
            name='Assemblethesets',
        ),
        migrations.DeleteModel(
            name='MacaronSet',
        ),
        migrations.DeleteModel(
            name='MacaronSetItem',
        ),
    ]
