# Generated by Django 5.0.7 on 2024-08-15 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_readykits_remove_macaronsetitem_macaron_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Macaron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Макарон',
                'verbose_name_plural': 'Макароны',
            },
        ),
        migrations.CreateModel(
            name='MacaronSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название набора')),
            ],
            options={
                'verbose_name': 'Собрать наборы',
                'verbose_name_plural': 'Собрать наборы',
            },
        ),
        migrations.CreateModel(
            name='MacaronSetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('macaron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.macaron', verbose_name='Собрать наборы')),
                ('macaron_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.macaronset', verbose_name='Набор')),
            ],
            options={
                'verbose_name': 'Элемент набора собрать наборы',
                'verbose_name_plural': 'Элементы наборов собрать наборы',
            },
        ),
        migrations.AddField(
            model_name='macaronset',
            name='macarons',
            field=models.ManyToManyField(through='polls.MacaronSetItem', to='polls.macaron', verbose_name='Собрать наборы'),
        ),
    ]
