# Generated by Django 5.1.1 on 2024-10-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_macaron_macaronset_macaronsetitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macaronsetitem',
            name='macaron_set',
        ),
        migrations.RemoveField(
            model_name='macaronsetitem',
            name='macaron',
        ),
        migrations.DeleteModel(
            name='MacaronSet',
        ),
        migrations.DeleteModel(
            name='MacaronSetItem',
        ),
    ]
