# Generated by Django 5.0.7 on 2024-08-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ваше имя')),
                ('phone', models.CharField(max_length=15, verbose_name='Ваш телефон')),
                ('delivery_method', models.CharField(choices=[('courier', 'Курьерская доставка'), ('pickup', 'Самовывоз')], max_length=10, verbose_name='Способ доставки')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес доставки')),
                ('delivery_date', models.DateField(verbose_name='Дата получения')),
                ('delivery_time', models.TimeField(verbose_name='Время')),
                ('comments', models.TextField(blank=True, max_length=500, verbose_name='Комментарии к заказу')),
                ('payment_method', models.CharField(choices=[('online', 'Оплата картой онлайн'), ('cash_on_delivery', 'Наличными при получении'), ('yandex_money', 'Яндекс деньги')], max_length=20, verbose_name='Метод оплаты')),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая сумма заказа вместе с доставкой')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
