# Generated by Django 5.1.1 on 2024-10-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=190, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Дополнительное',
                'verbose_name_plural': 'Дополнительные',
            },
        ),
        migrations.CreateModel(
            name='ChooseYourTastes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_name_of_the_taste', models.CharField(max_length=100, verbose_name='Название вкуса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Выберите вкус',
                'verbose_name_plural': 'Выберите вкус',
            },
        ),
        migrations.CreateModel(
            name='SelectTheQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение')),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Выберите количество',
                'verbose_name_plural': 'Выберите количество',
            },
        ),
    ]
