# Generated by Django 5.1.1 on 2024-10-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='chooseyourtastes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='selectthequantity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='изображение'),
        ),
    ]
