# Generated by Django 5.1.1 on 2024-10-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0002_alter_additional_image_alter_chooseyourtastes_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='chooseyourtastes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='selectthequantity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение'),
        ),
    ]
